/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as IndexImport } from "./routes/index"
import { Route as PlayerIndexImport } from "./routes/player/index"
import { Route as PlayerPlayerImport } from "./routes/player/player"

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const PlayerIndexRoute = PlayerIndexImport.update({
  id: "/player/",
  path: "/player/",
  getParentRoute: () => rootRoute,
} as any)

const PlayerPlayerRoute = PlayerPlayerImport.update({
  id: "/player/player",
  path: "/player/player",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/player/player": {
      id: "/player/player"
      path: "/player/player"
      fullPath: "/player/player"
      preLoaderRoute: typeof PlayerPlayerImport
      parentRoute: typeof rootRoute
    }
    "/player/": {
      id: "/player/"
      path: "/player"
      fullPath: "/player"
      preLoaderRoute: typeof PlayerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/player/player": typeof PlayerPlayerRoute
  "/player": typeof PlayerIndexRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/player/player": typeof PlayerPlayerRoute
  "/player": typeof PlayerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/player/player": typeof PlayerPlayerRoute
  "/player/": typeof PlayerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/player/player" | "/player"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/player/player" | "/player"
  id: "__root__" | "/" | "/player/player" | "/player/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerPlayerRoute: typeof PlayerPlayerRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerPlayerRoute: PlayerPlayerRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/player/player",
        "/player/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/player/player": {
      "filePath": "player/player.tsx"
    },
    "/player/": {
      "filePath": "player/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
